import Footer from "@/components/home/Footer/Footer";
import Header from "@/page/layout/HeaderCustomer/Header";
import HeaderBottom from "@/page/layout/HeaderCustomer/HeaderBottom";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <HeaderBottom />
      {children}
      <Footer />
    </div>
  );
}
